development:
  sessions:
    default:
      database: context_manager_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: context_manager_test
      hosts:
        - localhost:27017